### ISSUE TITLE
2.2.0 Jar seems to include an incoherent version number in its pom

### ISSUE THREAD

**Issue by nhumblot** [google/summit-ast#57]
## Expected Behavior

The `<version>` and `<tag>` XML tags have the `2.2.0` value

## Actual Behavior

The `<version>` and `<tag>` XML tags have the `2.2.0\n` value, not matching the actual version https://mvnrepository.com/artifact/com.google.summit/summit-ast/2.2.0

## Steps to Reproduce the Problem

1. [Download the jar of the 2.2.0 version on Maven central](https://repo1.maven.org/maven2/com/google/summit/summit-ast/2.2.0/summit-ast-2.2.0.jar)
1. `unzip summit-ast-2.2.0.jar`
1. `cat META-INF/maven/com.google.summit/summit-ast/pom.xml`

This got identified during an investigation of an error faced during the execution of OWASP DependencyCheck: https://github.com/jeremylong/DependencyCheck/issues/6688#issuecomment-2138489883

## Specifications

- Version: `2.2.0`
- Platform: Linux

**Comment by aaronhurst-google** [comment]
I’ve caught this a few times, but this one escaped.

The https://github.com/vaticle/bazel-distribution that generates pom.xml includes the exact contents of VERSION… including the trailing newline that most text editors will add by default.

I would prefer to move away from this dependency.

**Comment by nhumblot** [comment]
Hi @aaronhurst-google :wave: 

Thank you for your answer.  Do you have an idea of what you would like to have as a replacement of this dependency? Would a PR, opened by a first time contributor, following these guidelines be considered if open?

**Comment by nhumblot** [comment]
Root cause in Bazel distribution has been identified: https://github.com/vaticle/bazel-distribution/issues/380

**Comment by farost** [comment]
Thank you for mentioning our issue!

As I understand, your problem comes from the `assemble_maven` rule, and its behavior has been [fixed](https://github.com/vaticle/bazel-distribution/pull/414). You can try updating [your dependency](https://github.com/google/summit-ast/blob/main/WORKSPACE#L51) to [this commit](https://github.com/vaticle/bazel-distribution/commit/8767cdec452c14274493c576a2955059ff17f2e4) and check if the issue is still relevant.
